### ISSUE TITLE
Empty Strings

### ISSUE THREAD

**Issue by Friedjof** [schliflo/schimpfwortgenerator#1]
There are empty strings in the bad-words.json like https://github.com/schliflo/schimpfwortgenerator/blob/gh-pages/bad-words.json#L6826

**Comment by schliflo** [comment]
Zefix!

Thanks for reporting this huge issue :)
Immediately went and fixed it.

**Comment by Friedjof** [comment]
**Herrgottssakaramentkreizkruzifixnoamol!**
It would be stupid if no swear word came out!
